const data = {
  activo: true,
  id: "a151U000004D9UWQA0",
  logo:
    "https://rosbacopartners.com/wp-content/uploads/2020/11/Logo-Modificado-para-Landing-min.png",
  name: "rosbacopartners.com/landing-MoodNiceto2Ang",
  proyecto: "a061U00000BlhikQAB",
  urlLanding: "https://rosbaco-landings.netlify.app/LandingNiceto2",
  modulos: [
    {
      recordType: "MENU",
      content: [
        {
          ancla: "Ubicación",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: null,
          contactoDescripcion: "<p>Ubicación</p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009I9lsQAC",
          landing: "a151U000004D9UWQA0",
          name: "Menu 1",
          ocultar: false,
          ordenInterno: "NaN",
          orden: 1.0,
          recordType: "0121U000000KV0VQAW",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "Ubicación",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen: "",
        },
        {
          ancla: "Formulario",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: null,
          contactoDescripcion: "<p>Contacto</p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009I9lxQAC",
          landing: "a151U000004D9UWQA0",
          name: "Menu 2",
          ocultar: false,
          ordenInterno: "NaN",
          orden: 1.0,
          recordType: "0121U000000KV0VQAW",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "Contacto",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen: "",
        },
        {
          ancla: "Texto Slider",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: null,
          contactoDescripcion: "<p>Amenities</p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009I9m7QAC",
          landing: "a151U000004D9UWQA0",
          name: "Menu 3 Am",
          ocultar: false,
          ordenInterno: "NaN",
          orden: 1.0,
          recordType: "0121U000000KV0VQAW",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "Amenities",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen: "",
        },
      ],
    },
    {
      recordType: "IMAGEN",
      content: [
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: null,
          contactoDescripcion: "<p></p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009I9m8QAC",
          landing: "a151U000004D9UWQA0",
          name: "Img ppal Fachada",
          ocultar: false,
          ordenInterno: "NaN",
          orden: 2.0,
          recordType: "0121U000000KV0GQAW",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen:
            "https://rosbacopartners.com/wp-content/uploads/2020/12/WhatsApp-Image-2020-12-17-at-3.59.51-PM.jpeg",
        },
      ],
    },
    {
      recordType: "MAPA_UNIDAD",
      content: [
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#F8F8F7",
          coordenadasSombra: null,
          contactoDescripcion:
            "<p>Departamentos 2 ambientes con balcón y amenities</p> <p>44 - 52 M2</p> <p>Edificio inteligente, construido con materiales de primera calidad, última tecnología en domótica, amenities, bajos cotos de expensas. Ideal para vivir y alquilar.</p>",
          descripcion:
            "Edificio inteligente, construido con materiales de primera calidad, última tecnología en domótica, amenities, bajos cotos de expensas. Ideal para vivir y alquilar.",
          descripcionhex: "#353532",
          descripcionalign: "left",
          id: "a161U000009I9mMQAS",
          landing: "a151U000004D9UWQA0",
          name: "Mapa Unidad (fachada edf)",
          ocultar: false,
          ordenInterno: null,
          orden: 3.0,
          recordType: "0121U000000KV0LQAW",
          subtitulo: "44 - 52 M2",
          subtitulohex: "#F1C40F",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "Departamentos 2 ambientes con balcón y amenities",
          titulohex: "#030303",
          tituloalign: "left",
          urlImagen:
            "https://rosbacopartners.com/wp-content/uploads/2020/12/Fachada-recorre.-Mapa-Unidad.jpg",
          unidadFuncional: null,
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: [1915, 2411, 2259, 2418, 2247, 2119, 1907, 2103],
          contactoDescripcion: "<p></p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009ICWJQA4",
          landing: "a151U000004D9UWQA0",
          name: "Mapa unidad piso 1 UF0101",
          ocultar: false,
          ordenInterno: null,
          orden: 3.0,
          recordType: "0121U000000KV0LQAW",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen: "",
          unidadFuncional: {
            ambiente: "2 Ambientes",
            estado: "Disponible",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 52.0,
            metrosCuadrados: 52.0,
            metrosCubiertos: 42.0,
            metrosDescubiertos: "NaN",
            metrosSemiCubiertos: 10.0,
            id: "a0L1U000004vtbwUAA",
            name: "UF 0101",
            piso: "1",
            imagenesUnidad: [
              {
                id: "a141U000003gHzNQAU",
                name: "UF0101 Imagen Niceto",
                orden: "",
                unidad: "a0L1U000004vtbwUAA",
                urlImagen:
                  "https://rosbacopartners.com/wp-content/uploads/2020/12/niceto9.jpg",
              },
            ],
          },
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: [1903, 2106, 1897, 2411, 1649, 2408, 1646, 2090],
          contactoDescripcion: "<p></p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009IBXwQAO",
          landing: "a151U000004D9UWQA0",
          name: "Mapa Unidad Piso 1 UF0102",
          ocultar: false,
          ordenInterno: null,
          orden: 3.0,
          recordType: "0121U000000KV0LQAW",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen: "",
          unidadFuncional: {
            ambiente: "Monoambiente",
            estado: "Disponible",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 45.0,
            metrosCuadrados: 45.0,
            metrosCubiertos: 40.0,
            metrosDescubiertos: "NaN",
            metrosSemiCubiertos: 5.0,
            id: "a0L1U000004vtbxUAA",
            name: "UF 0102",
            piso: "1",
            imagenesUnidad: [
              {
                id: "a141U000003gHzDQAU",
                name: "UF0102 Imagen Unidad",
                orden: "",
                unidad: "a0L1U000004vtbxUAA",
                urlImagen:
                  "https://rosbacopartners.com/wp-content/uploads/2020/12/niceto11.jpg",
              },
            ],
          },
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: [1887, 2151, 1884, 1925, 2221, 1966, 2228, 2189],
          contactoDescripcion: "<p></p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009Vx47QAC",
          landing: "a151U000004D9UWQA0",
          name: "Mapa Unidad Piso 2 UF0201",
          ocultar: false,
          ordenInterno: null,
          orden: 3.0,
          recordType: "0121U000000KV0LQAW",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen: "",
          unidadFuncional: {
            ambiente: "2 Ambientes",
            estado: "Disponible",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 52.0,
            metrosCuadrados: 52.0,
            metrosCubiertos: 42.0,
            metrosDescubiertos: "NaN",
            metrosSemiCubiertos: 10.0,
            id: "a0L1U000004vtcNUAQ",
            name: "UF 0201",
            piso: "2",
            imagenesUnidad: [
              {
                id: "a141U000003geT9QAI",
                name: "UF0201",
                orden: "",
                unidad: "a0L1U000004vtcNUAQ",
                urlImagen:
                  "https://rosbacopartners.com/wp-content/uploads/2020/12/niceto10.jpg",
              },
            ],
          },
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: [1862, 1922, 1859, 2166, 1614, 2141, 1623, 1896],
          contactoDescripcion: "<p></p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009Vx4CQAS",
          landing: "a151U000004D9UWQA0",
          name: "Mapa Unidad Piso 2  UF0202",
          ocultar: false,
          ordenInterno: null,
          orden: 3.0,
          recordType: "0121U000000KV0LQAW",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen: "",
          unidadFuncional: {
            ambiente: "Monoambiente",
            estado: "Vendida",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 45.0,
            metrosCuadrados: 45.0,
            metrosCubiertos: 40.0,
            metrosDescubiertos: "NaN",
            metrosSemiCubiertos: 5.0,
            id: "a0L1U000004vtcJUAQ",
            name: "UF 0202",
            piso: "2",
            imagenesUnidad: [
              {
                id: "a141U000003geTEQAY",
                name: "UF0202",
                orden: "",
                unidad: "a0L1U000004vtcJUAQ",
                urlImagen:
                  "https://rosbacopartners.com/wp-content/uploads/2020/12/niceto10.jpg",
              },
            ],
          },
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: [1875, 1683, 1875, 1899, 2240, 1950, 2244, 1747],
          contactoDescripcion: "<p></p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009Vx4HQAS",
          landing: "a151U000004D9UWQA0",
          name: "Mapa Unidad Piso 3 UF0301",
          ocultar: false,
          ordenInterno: null,
          orden: 3.0,
          recordType: "0121U000000KV0LQAW",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen: "",
          unidadFuncional: {
            ambiente: "2 Ambientes",
            estado: "Vendida",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 52.0,
            metrosCuadrados: 52.0,
            metrosCubiertos: 42.0,
            metrosDescubiertos: "NaN",
            metrosSemiCubiertos: 10.0,
            id: "a0L1U000004vtchUAA",
            name: "UF 0301",
            piso: "3",
            imagenesUnidad: [
              {
                id: "a141U000003geTOQAY",
                name: "UF0301",
                orden: "",
                unidad: "a0L1U000004vtchUAA",
                urlImagen:
                  "https://rosbacopartners.com/wp-content/uploads/2020/12/niceto11.jpg",
              },
            ],
          },
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: [1859, 1677, 1865, 1906, 1646, 1877, 1646, 1645],
          contactoDescripcion: "<p></p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009Vx4MQAS",
          landing: "a151U000004D9UWQA0",
          name: "Mapa Unidad Piso 3 UF0302",
          ocultar: false,
          ordenInterno: null,
          orden: 3.0,
          recordType: "0121U000000KV0LQAW",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen: "",
          unidadFuncional: {
            ambiente: "Monoambiente",
            estado: "Vendida",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 45.0,
            metrosCuadrados: 45.0,
            metrosCubiertos: 40.0,
            metrosDescubiertos: "NaN",
            metrosSemiCubiertos: 5.0,
            id: "a0L1U000004vtciUAA",
            name: "UF 0302",
            piso: "3",
            imagenesUnidad: [
              {
                id: "a141U000003geTTQAY",
                name: "UF 0302",
                orden: "",
                unidad: "a0L1U000004vtciUAA",
                urlImagen:
                  "https://rosbacopartners.com/wp-content/uploads/2020/12/niceto2.jpg",
              },
            ],
          },
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: [2263, 1524, 2244, 1731, 1884, 1664, 1894, 1438],
          contactoDescripcion: "<p></p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009Vx4RQAS",
          landing: "a151U000004D9UWQA0",
          name: "Mapa Unidad Piso 4 UF0401",
          ocultar: false,
          ordenInterno: null,
          orden: 3.0,
          recordType: "0121U000000KV0LQAW",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen: "",
          unidadFuncional: {
            ambiente: "2 Ambientes",
            estado: "Disponible",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 52.0,
            metrosCuadrados: 52.0,
            metrosCubiertos: 42.0,
            metrosDescubiertos: "NaN",
            metrosSemiCubiertos: 10.0,
            id: "a0L1U000004vtcOUAQ",
            name: "UF 0401",
            piso: "4",
            imagenesUnidad: [
              {
                id: "a141U000003geTYQAY",
                name: "UF 0401",
                orden: "",
                unidad: "a0L1U000004vtcOUAQ",
                urlImagen:
                  "https://rosbacopartners.com/wp-content/uploads/2020/12/niceto2.jpg",
              },
            ],
          },
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: [1872, 1428, 1865, 1670, 1636, 1632, 1646, 1381],
          contactoDescripcion: "<p></p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009VxGzQAK",
          landing: "a151U000004D9UWQA0",
          name: "Mapa Unidad Piso 4 UF0402",
          ocultar: false,
          ordenInterno: null,
          orden: 3.0,
          recordType: "0121U000000KV0LQAW",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen: "",
          unidadFuncional: {
            ambiente: "Monoambiente",
            estado: "Disponible",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 45.0,
            metrosCuadrados: 45.0,
            metrosCubiertos: 40.0,
            metrosDescubiertos: "NaN",
            metrosSemiCubiertos: 5.0,
            id: "a0L1U000004vtcwUAA",
            name: "UF 0402",
            piso: "4",
            imagenesUnidad: [
              {
                id: "a141U000003geTUQAY",
                name: "UF 0402",
                orden: "",
                unidad: "a0L1U000004vtcwUAA",
                urlImagen:
                  "https://rosbacopartners.com/wp-content/uploads/2020/12/niceto2.jpg",
              },
            ],
          },
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: [2253, 1308, 2253, 1508, 1887, 1419, 1884, 1206],
          contactoDescripcion: "<p></p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009VxH4QAK",
          landing: "a151U000004D9UWQA0",
          name: "Mapa Unidad Piso 5 UF0501",
          ocultar: false,
          ordenInterno: null,
          orden: 3.0,
          recordType: "0121U000000KV0LQAW",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen: "",
          unidadFuncional: {
            ambiente: "2 Ambientes",
            estado: "Vendida",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 52.0,
            metrosCuadrados: 52.0,
            metrosCubiertos: 42.0,
            metrosDescubiertos: "NaN",
            metrosSemiCubiertos: 10.0,
            id: "a0L1U000004vtcEUAQ",
            name: "UF 0501",
            piso: "5",
            imagenesUnidad: [
              {
                id: "a141U000003geTiQAI",
                name: "UF 0501",
                orden: "",
                unidad: "a0L1U000004vtcEUAQ",
                urlImagen:
                  "https://rosbacopartners.com/wp-content/uploads/2020/12/imagen-niceto-1.jpg",
              },
            ],
          },
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: [1859, 1203, 1862, 1416, 1633, 1362, 1652, 1139],
          contactoDescripcion: "<p></p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009VxH0QAK",
          landing: "a151U000004D9UWQA0",
          name: "Mapa Unidad piso 5 UF0502",
          ocultar: false,
          ordenInterno: null,
          orden: 3.0,
          recordType: "0121U000000KV0LQAW",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen: "",
          unidadFuncional: {
            ambiente: "Monoambiente",
            estado: "Vendida",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 45.0,
            metrosCuadrados: 45.0,
            metrosCubiertos: 40.0,
            metrosDescubiertos: "NaN",
            metrosSemiCubiertos: 5.0,
            id: "a0L1U000004vtd2UAA",
            name: "UF 0502",
            piso: "5",
            imagenesUnidad: [
              {
                id: "a141U000003geTdQAI",
                name: "UF 0502",
                orden: "",
                unidad: "a0L1U000004vtd2UAA",
                urlImagen:
                  "https://rosbacopartners.com/wp-content/uploads/2020/12/imagen-niceto-1.jpg",
              },
            ],
          },
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: [2244, 1075, 2247, 1288, 1868, 1180, 1881, 961],
          contactoDescripcion: "<p></p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009VxH9QAK",
          landing: "a151U000004D9UWQA0",
          name: "Mapa Unidad Piso 6 UF0601",
          ocultar: false,
          ordenInterno: null,
          orden: 3.0,
          recordType: "0121U000000KV0LQAW",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen: "",
          unidadFuncional: {
            ambiente: "2 Ambientes",
            estado: "Disponible",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 52.0,
            metrosCuadrados: 52.0,
            metrosCubiertos: 42.0,
            metrosDescubiertos: "NaN",
            metrosSemiCubiertos: 10.0,
            id: "a0L1U000004vtfqUAA",
            name: "UF 0601",
            piso: "6",
            imagenesUnidad: [
              {
                id: "a141U000003geTsQAI",
                name: "UF 0601",
                orden: "",
                unidad: "a0L1U000004vtfqUAA",
                urlImagen:
                  "https://rosbacopartners.com/wp-content/uploads/2020/12/niceto8.jpg",
              },
            ],
          },
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: [1862, 948, 1859, 1180, 1646, 1123, 1658, 884],
          contactoDescripcion: "<p></p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009VxH5QAK",
          landing: "a151U000004D9UWQA0",
          name: "Mapa Unidad Piso 6 UF0602",
          ocultar: false,
          ordenInterno: null,
          orden: 3.0,
          recordType: "0121U000000KV0LQAW",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen: "",
          unidadFuncional: {
            ambiente: "Monoambiente",
            estado: "Vendida",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 45.0,
            metrosCuadrados: 45.0,
            metrosCubiertos: 40.0,
            metrosDescubiertos: "NaN",
            metrosSemiCubiertos: 5.0,
            id: "a0L1U000004vtg0UAA",
            name: "UF 0602",
            piso: "6",
            imagenesUnidad: [
              {
                id: "a141U000003geTnQAI",
                name: "UF0602",
                orden: "",
                unidad: "a0L1U000004vtg0UAA",
                urlImagen:
                  "https://rosbacopartners.com/wp-content/uploads/2020/12/imagen-niceto-1.jpg",
              },
            ],
          },
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: [2244, 865, 2244, 1063, 1891, 948, 1891, 725],
          contactoDescripcion: "<p></p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009VxHAQA0",
          landing: "a151U000004D9UWQA0",
          name: "Mapa Unidad Piso 7 UF0701",
          ocultar: false,
          ordenInterno: null,
          orden: 3.0,
          recordType: "0121U000000KV0LQAW",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen: "",
          unidadFuncional: {
            ambiente: "2 Ambientes",
            estado: "Disponible",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 52.0,
            metrosCuadrados: 52.0,
            metrosCubiertos: 42.0,
            metrosDescubiertos: "NaN",
            metrosSemiCubiertos: 10.0,
            id: "a0L1U000004vtgFUAQ",
            name: "UF 0701",
            piso: "7",
            imagenesUnidad: [
              {
                id: "a141U000003geTxQAI",
                name: "UF 0701",
                orden: "",
                unidad: "a0L1U000004vtgFUAQ",
                urlImagen:
                  "https://rosbacopartners.com/wp-content/uploads/2020/12/niceto-4.jpg",
              },
            ],
          },
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: [1868, 717, 1875, 932, 1617, 872, 1614, 681],
          contactoDescripcion: "<p></p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009VxHBQA0",
          landing: "a151U000004D9UWQA0",
          name: "Mapa Unidad Piso 7 UF0702",
          ocultar: false,
          ordenInterno: null,
          orden: 3.0,
          recordType: "0121U000000KV0LQAW",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen: "",
          unidadFuncional: {
            ambiente: "Monoambiente",
            estado: "Disponible",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 45.0,
            metrosCuadrados: 45.0,
            metrosCubiertos: 40.0,
            metrosDescubiertos: "NaN",
            metrosSemiCubiertos: 5.0,
            id: "a0L1U000004vtgKUAQ",
            name: "UF 0702",
            piso: "7",
            imagenesUnidad: [
              {
                id: "a141U000003geU2QAI",
                name: "UF 0702",
                orden: "",
                unidad: "a0L1U000004vtgKUAQ",
                urlImagen:
                  "https://rosbacopartners.com/wp-content/uploads/2020/12/niceto-4.jpg",
              },
            ],
          },
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: [2237, 639, 2244, 846, 1878, 694, 1878, 471],
          contactoDescripcion: "<p></p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009VxHOQA0",
          landing: "a151U000004D9UWQA0",
          name: "Mapa Unidad Piso 8 UF0801",
          ocultar: false,
          ordenInterno: null,
          orden: 3.0,
          recordType: "0121U000000KV0LQAW",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen: "",
          unidadFuncional: {
            ambiente: "2 Ambientes",
            estado: "Reservado Desarrolladora",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 49.0,
            metrosCuadrados: 49.0,
            metrosCubiertos: 39.0,
            metrosDescubiertos: "NaN",
            metrosSemiCubiertos: 10.0,
            id: "a0L1U000004vtgZUAQ",
            name: "UF 0801",
            piso: "8",
            imagenesUnidad: [
              {
                id: "a141U000003geU7QAI",
                name: "UF 0801",
                orden: "",
                unidad: "a0L1U000004vtgZUAQ",
                urlImagen:
                  "https://rosbacopartners.com/wp-content/uploads/2020/12/niceto3.jpg",
              },
            ],
          },
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: [1856, 506, 1865, 697, 1598, 662, 1595, 464],
          contactoDescripcion: "<p></p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009VxHTQA0",
          landing: "a151U000004D9UWQA0",
          name: "Mapa Unidad Piso 8 UF0802",
          ocultar: false,
          ordenInterno: null,
          orden: 3.0,
          recordType: "0121U000000KV0LQAW",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen: "",
          unidadFuncional: {
            ambiente: "Monoambiente",
            estado: "Reservado Desarrolladora",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 43.0,
            metrosCuadrados: 43.0,
            metrosCubiertos: 34.0,
            metrosDescubiertos: "NaN",
            metrosSemiCubiertos: 9.0,
            id: "a0L1U000007L7h3UAC",
            name: "UF 0802",
            piso: "8",
            imagenesUnidad: [
              {
                id: "a141U000003geUCQAY",
                name: "UF 0802",
                orden: "",
                unidad: "a0L1U000007L7h3UAC",
                urlImagen:
                  "https://rosbacopartners.com/wp-content/uploads/2020/12/niceto3.jpg",
              },
            ],
          },
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: [1875, 321, 1878, 461, 2231, 623, 2238, 477],
          contactoDescripcion: "<p></p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009VxHPQA0",
          landing: "a151U000004D9UWQA0",
          name: "Mapa Unidad Pison 9 UF0901",
          ocultar: false,
          ordenInterno: null,
          orden: 3.0,
          recordType: "0121U000000KV0LQAW",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen: "",
          unidadFuncional: {
            ambiente: "2 Ambientes",
            estado: "Reservado Desarrolladora",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 61.0,
            metrosCuadrados: 61.0,
            metrosCubiertos: 40.0,
            metrosDescubiertos: "NaN",
            metrosSemiCubiertos: 21.0,
            id: "a0L1U0000064hOXUAY",
            name: "UF 0901",
            piso: "9",
            imagenesUnidad: [
              {
                id: "a141U000003geUHQAY",
                name: "UF 0901",
                orden: "",
                unidad: "a0L1U0000064hOXUAY",
                urlImagen:
                  "https://rosbacopartners.com/wp-content/uploads/2020/11/04-DOS-AMBIENTES-3.jpg",
              },
            ],
          },
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: [1592, 299, 1856, 328, 1849, 484, 1585, 458],
          contactoDescripcion: "<p></p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009VxHYQA0",
          landing: "a151U000004D9UWQA0",
          name: "Mapa Unidad Piso 9 UF0902",
          ocultar: false,
          ordenInterno: null,
          orden: 3.0,
          recordType: "0121U000000KV0LQAW",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen: "",
          unidadFuncional: {
            ambiente: "Monoambiente",
            estado: "Reservado Desarrolladora",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 26.0,
            metrosCuadrados: 26.0,
            metrosCubiertos: 24.0,
            metrosDescubiertos: "NaN",
            metrosSemiCubiertos: 2.0,
            id: "a0L1U0000064hOSUAY",
            name: "UF 0902",
            piso: "9",
            imagenesUnidad: [
              {
                id: "a141U000003geUMQAY",
                name: "UF 0902",
                orden: "",
                unidad: "a0L1U0000064hOSUAY",
                urlImagen:
                  "https://rosbacopartners.com/wp-content/uploads/2020/11/04-DOS-AMBIENTES-3.jpg",
              },
            ],
          },
        },
      ],
    },
    {
      recordType: "TEXTO_SLIDER",
      content: [
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#F8F8F7",
          coordenadasSombra: null,
          contactoDescripcion:
            "<p>Diseños Modernos</p> <p>Espacios amplios y luminosos. Todas las unidades cuentan con balcón y hermosa vista panorámica.</p> <p>Los bajos costos de mantenimiento, última tecnología, el gran atractivo inmobiliario y la velocidad del retorno esperado, además del sello de garantía de la marca Rosbaco & Partners, hacen de Mood® Niceto Vega tu posible primera vivienda.</p>",
          descripcion:
            "Los bajos costos de mantenimiento, última tecnología, el gran atractivo inmobiliario y la velocidad del retorno esperado, además del sello de garantía de la marca Rosbaco & Partners, hacen de Mood® Niceto Vega tu posible primera vivienda.",
          descripcionhex: "#353532",
          descripcionalign: "left",
          id: "a161U000009ICfbQAG",
          landing: "a151U000004D9UWQA0",
          name: "Texto slider Dpto. 1",
          ocultar: true,
          ordenInterno: "NaN",
          orden: 4.0,
          recordType: "0121U000000KV0pQAG",
          subtitulo:
            "Espacios amplios y luminosos. Todas las unidades cuentan con balcón y hermosa vista panorámica.",
          subtitulohex: "#F1C40F",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "Diseños Modernos",
          titulohex: "#030303",
          tituloalign: "left",
          urlImagen:
            "https://rosbacopartners.com/wp-content/uploads/2020/12/niceto11.jpg",
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#F8F8F7",
          coordenadasSombra: null,
          contactoDescripcion:
            "<p>Ubicación Estratégica</p> <p>Conectividad óptima por encontrarse a pasos de importantes Avenidas</p> <p>Ubicado en Palermo Hollywood una de las zonas más buscadas por el público joven y dinámico, Mood Niceto Vega es una propuesta innovadora, moderna, joven, colaborativa y sustentable que responde a los nuevos estilos y propuestas de vida urbana.</p>",
          descripcion:
            "Ubicado en Palermo Hollywood una de las zonas más buscadas por el público joven y dinámico, Mood Niceto Vega es una propuesta innovadora, moderna, joven, colaborativa y sustentable que responde a los nuevos estilos y propuestas de vida urbana.",
          descripcionhex: "#353532",
          descripcionalign: "left",
          id: "a161U000009ICfCQAW",
          landing: "a151U000004D9UWQA0",
          name: "Texto Slider Depto 2",
          ocultar: true,
          ordenInterno: "NaN",
          orden: 4.0,
          recordType: "0121U000000KV0pQAG",
          subtitulo:
            "Conectividad óptima por encontrarse a pasos de importantes Avenidas",
          subtitulohex: "#F1C40F",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "Ubicación Estratégica",
          titulohex: "#030303",
          tituloalign: "left",
          urlImagen:
            "https://rosbacopartners.com/wp-content/uploads/2020/12/niceto9.jpg",
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#F8F8F7",
          coordenadasSombra: null,
          contactoDescripcion:
            "<p>ECO-FRIENDLY</p> <p>Diseños Modernos y Sustentables</p> <p>Cumple con nuestro compromiso de sustentabilidad con un uso súper eficiente de los recursos, reduciendo el consumo de luz, agua o gas.</p>",
          descripcion:
            "Cumple con nuestro compromiso de sustentabilidad con un uso súper eficiente de los recursos, reduciendo el consumo de luz, agua o gas.",
          descripcionhex: "#353532",
          descripcionalign: "left",
          id: "a161U000009ICfRQAW",
          landing: "a151U000004D9UWQA0",
          name: "Texto slider Depto. 3",
          ocultar: true,
          ordenInterno: "NaN",
          orden: 4.0,
          recordType: "0121U000000KV0pQAG",
          subtitulo: "Diseños Modernos y Sustentables",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "ECO-FRIENDLY",
          titulohex: "#030303",
          tituloalign: "left",
          urlImagen:
            "https://rosbacopartners.com/wp-content/uploads/2020/12/niceto3.jpg",
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: null,
          contactoDescripcion: "<p></p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009VyIlQAK",
          landing: "a151U000004D9UWQA0",
          name: "Texto Slider Depto. 4",
          ocultar: false,
          ordenInterno: "NaN",
          orden: 4.0,
          recordType: "0121U000000KV0pQAG",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen:
            "https://rosbacopartners.com/wp-content/uploads/2020/12/amenitiesniceto.COMP_.jpg",
        },
      ],
    },
    {
      recordType: "MAPA_UBICACION",
      content: [
        {
          ancla: "Ubicación",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#F8F8F7",
          coordenadasSombra: null,
          contactoDescripcion: "<p></p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009I9mRQAS",
          landing: "a151U000004D9UWQA0",
          name: "Mapa Ubicación",
          ocultar: false,
          ordenInterno: null,
          orden: 5.0,
          recordType: "0121U000000KV0QQAW",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen:
            "https://rosbacopartners.com/wp-content/uploads/2020/12/Mapa-Ubicacion-editado.jpg",
          sitiosInteres: [
            {
              categoria: "colegio",
              content: [
                {
                  categoria: "colegio",
                  descripcion: "Universidad Nacional de San Martín Pascal",
                  id: "a171U00000AKb3gQAD",
                  item: "Universidad",
                  modulo: "a161U000009I9mRQAS",
                  name: "Educación",
                },
              ],
            },
            {
              categoria: "gym",
              content: [
                {
                  categoria: "gym",
                  descripcion: "",
                  id: "a171U00000AKaxSQAT",
                  item: "Sport Club Tuluka",
                  modulo: "a161U000009I9mRQAS",
                  name: "Gym",
                },
              ],
            },
            {
              categoria: "plaza",
              content: [
                {
                  categoria: "plaza",
                  descripcion: "Plaza Serrano",
                  id: "a171U00000AKb3lQAD",
                  item: "Plazas, parques y ferias",
                  modulo: "a161U000009I9mRQAS",
                  name: "Plazas, Parques y Espacios de Recreación",
                },
              ],
            },
            {
              categoria: "restaurante",
              content: [
                {
                  categoria: "restaurante",
                  descripcion: "",
                  id: "a171U00000AKayAQAT",
                  item:
                    "Bares, Restorantes y Salones de Eventos. (Zona Comercial)",
                  modulo: "a161U000009I9mRQAS",
                  name: "Entretenimiento",
                },
              ],
            },
            {
              categoria: "shopping",
              content: [
                {
                  categoria: "shopping",
                  descripcion: "Mercado de las pulgas, Mercado Punto Verde",
                  id: "a171U00000AKayFQAT",
                  item: "Shopping y Mercados Populares",
                  modulo: "a161U000009I9mRQAS",
                  name: "Shopping",
                },
              ],
            },
          ],
        },
      ],
    },
    {
      recordType: "SLIDER",
      content: [
        {
          ancla: "Texto Slider",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#F8F8F7",
          coordenadasSombra: null,
          contactoDescripcion: "<p></p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#353532",
          descripcionalign: "left",
          id: "a161U000009VyICQA0",
          landing: "a151U000004D9UWQA0",
          name: "slider amenities 1",
          ocultar: false,
          ordenInterno: "NaN",
          orden: 6.0,
          recordType: "0121U000000KV0aQAG",
          subtitulo: "",
          subtitulohex: "#F1C40F",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "",
          titulohex: "#030303",
          tituloalign: "left",
          urlImagen:
            "https://rosbacopartners.com/wp-content/uploads/2020/12/NICETO12.jpg",
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#F8F8F",
          coordenadasSombra: null,
          contactoDescripcion: "<p></p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009VyIHQA0",
          landing: "a151U000004D9UWQA0",
          name: "Slider amenities 2",
          ocultar: false,
          ordenInterno: "NaN",
          orden: 6.0,
          recordType: "0121U000000KV0aQAG",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen:
            "https://rosbacopartners.com/wp-content/uploads/2020/12/NICETO13.jpg",
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#F8F8F",
          coordenadasSombra: null,
          contactoDescripcion: "<p></p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009VyIMQA0",
          landing: "a151U000004D9UWQA0",
          name: "Slider amenities 3",
          ocultar: false,
          ordenInterno: "NaN",
          orden: 6.0,
          recordType: "0121U000000KV0aQAG",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen:
            "https://rosbacopartners.com/wp-content/uploads/2020/12/NICETO-14.jpg",
        },
      ],
    },
    {
      recordType: "TEXTO_SLIDER",
      content: [
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#F8F8F7",
          coordenadasSombra: null,
          contactoDescripcion:
            "<p>Comunidad Mood</p> <p></p> <p>Pensado para un público moderno y descontracturado. Mood es una propuesta innovadora, moderna, joven, colaborativa y sustentable que responde a los nuevos estilos y propuestas de vida urbana.</p>",
          descripcion:
            "Pensado para un público moderno y descontracturado. Mood es una propuesta innovadora, moderna, joven, colaborativa y sustentable que responde a los nuevos estilos y propuestas de vida urbana.",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009I9mwQAC",
          landing: "a151U000004D9UWQA0",
          name: "Texto Slider Comunidad 1",
          ocultar: false,
          ordenInterno: "NaN",
          orden: 7.0,
          recordType: "0121U000000KV0pQAG",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "Comunidad Mood",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen:
            "https://rosbacopartners.com/wp-content/uploads/2020/11/comunidad-1.jpg",
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: null,
          contactoDescripcion:
            "<p>Comunidad Mood</p> <p></p> <p>Te ofrece la experiencia innovadora de vivir en un entorno dinámico donde estar conectado es mejor.  Al ser parte de la Comunidad MOOD vas a acceder a servicios de vida comunitaria mediante un Building Manager que te permite sumar a espacios comunitarios</p>",
          descripcion:
            "Te ofrece la experiencia innovadora de vivir en un entorno dinámico donde estar conectado es mejor.  Al ser parte de la Comunidad MOOD vas a acceder a servicios de vida comunitaria mediante un Building Manager que te permite sumar a espacios comunitarios",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009I9nGQAS",
          landing: "a151U000004D9UWQA0",
          name: "Text slider comunidad 2",
          ocultar: false,
          ordenInterno: "NaN",
          orden: 7.0,
          recordType: "0121U000000KV0pQAG",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "Comunidad Mood",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen:
            "https://rosbacopartners.com/wp-content/uploads/2020/11/comunidad-2.jpg",
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: null,
          contactoDescripcion:
            "<p>¡FORMÁ PARTE DE LA COMUNIDAD MOOD!</p> <p>¡Disfruta y aprovecha las ventajas de tener un espacio para relacionarte con los demás!</p> <p>Vas a acceder a servicios de vida comunitaria mediante un Building Manager que te permite sumar a espacios comunitarios de otros MOOD.</p>",
          descripcion:
            "Vas a acceder a servicios de vida comunitaria mediante un Building Manager que te permite sumar a espacios comunitarios de otros MOOD.",
          descripcionhex: "#353532",
          descripcionalign: "left",
          id: "a161U000009I9nYQAS",
          landing: "a151U000004D9UWQA0",
          name: "text slider comunidad3",
          ocultar: false,
          ordenInterno: "NaN",
          orden: 7.0,
          recordType: "0121U000000KV0pQAG",
          subtitulo:
            "¡Disfruta y aprovecha las ventajas de tener un espacio para relacionarte con los demás!",
          subtitulohex: "#F1C40F",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "¡FORMÁ PARTE DE LA COMUNIDAD MOOD!",
          titulohex: "#030303",
          tituloalign: "left",
          urlImagen:
            "https://rosbacopartners.com/wp-content/uploads/2020/11/comunidad-3.jpg",
        },
      ],
    },
    {
      recordType: "FORMULARIO",
      content: [
        {
          ancla: "Formulario",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#F8F8F7",
          coordenadasSombra: null,
          contactoDescripcion:
            "<p>¡Consultá nuestros planes de financiación en pesos y flexibilidad de pago!</p> <p>Edificio inteligente con balcón en todas las unidades.</p> <p>Excelente ubicación con amenities y bajos costos de mantenimiento</p>",
          descripcion:
            "Excelente ubicación con amenities y bajos costos de mantenimiento",
          descripcionhex: "#353532",
          descripcionalign: "left",
          id: "a161U000009I9niQAC",
          landing: "a151U000004D9UWQA0",
          name: "Formulario",
          ocultar: false,
          ordenInterno: "NaN",
          orden: 8.0,
          recordType: "0121U000000KV0BQAW",
          subtitulo: "Edificio inteligente con balcón en todas las unidades.",
          subtitulohex: "#F1C40F",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo:
            "¡Consultá nuestros planes de financiación en pesos y flexibilidad de pago!",
          titulohex: "#030303",
          tituloalign: "left",
          urlImagen: "",
        },
      ],
    },
    {
      recordType: "FOOTER",
      content: [
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: null,
          contactoDescripcion: "<p></p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009I9lnQAC",
          landing: "a151U000004D9UWQA0",
          name: "Footer (img final)",
          ocultar: false,
          ordenInterno: "NaN",
          orden: 10.0,
          recordType: "0121U000000KV06QAG",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen:
            "https://rosbacopartners.com/wp-content/uploads/2020/11/02-FACHADA-NOCHE-1.jpg",
        },
      ],
    },
    {
      recordType: "MAPA_UNIDAD",
      content: [
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: null,
          contactoDescripcion:
            "<p>2 ambientes con balcón</p> <p>Total: 47m2</p> <p>40m2 Cubiertos - 7m2</p>",
          descripcion: "40m2 Cubiertos - 7m2",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009W6IkQAK",
          landing: "a151U000004D9UWQA0",
          name: "UF 0304",
          ocultar: true,
          ordenInterno: null,
          orden: "NaN",
          recordType: "0121U000000KV0LQAW",
          subtitulo: "Total: 47m2",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "2 ambientes con balcón",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen:
            "https://rosbacopartners.com/wp-content/uploads/2020/12/niceto11.jpg",
          unidadFuncional: {
            ambiente: "2 Ambientes",
            estado: "Vendida",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 47.0,
            metrosCuadrados: 47.0,
            metrosCubiertos: 40.0,
            metrosDescubiertos: "NaN",
            metrosSemiCubiertos: 7.0,
            id: "a0L1U000004vtcrUAA",
            name: "UF 0304",
            piso: "3",
            imagenesUnidad: null,
          },
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: null,
          contactoDescripcion: "<p></p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009W6JOQA0",
          landing: "a151U000004D9UWQA0",
          name: "UF 0703",
          ocultar: true,
          ordenInterno: null,
          orden: "NaN",
          recordType: "0121U000000KV0LQAW",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen: "",
          unidadFuncional: {
            ambiente: "Monoambiente",
            estado: "Disponible",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 44.0,
            metrosCuadrados: 44.0,
            metrosCubiertos: 40.0,
            metrosDescubiertos: "NaN",
            metrosSemiCubiertos: 4.0,
            id: "a0L1U000004vtgPUAQ",
            name: "UF 0703",
            piso: "7",
            imagenesUnidad: null,
          },
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: null,
          contactoDescripcion: "<p></p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009W6JTQA0",
          landing: "a151U000004D9UWQA0",
          name: "UF 0803",
          ocultar: true,
          ordenInterno: null,
          orden: "NaN",
          recordType: "0121U000000KV0LQAW",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen: "",
          unidadFuncional: {
            ambiente: "2 Ambientes",
            estado: "Reservado Desarrolladora",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 44.0,
            metrosCuadrados: 44.0,
            metrosCubiertos: 40.0,
            metrosDescubiertos: "NaN",
            metrosSemiCubiertos: 4.0,
            id: "a0L1U000004vtgeUAA",
            name: "UF 0803",
            piso: "8",
            imagenesUnidad: null,
          },
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: null,
          contactoDescripcion: "<p></p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009W6J1QAK",
          landing: "a151U000004D9UWQA0",
          name: "UF 0603",
          ocultar: true,
          ordenInterno: null,
          orden: "NaN",
          recordType: "0121U000000KV0LQAW",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen: "",
          unidadFuncional: {
            ambiente: "Monoambiente",
            estado: "Vendida",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 44.0,
            metrosCuadrados: 44.0,
            metrosCubiertos: 40.0,
            metrosDescubiertos: "NaN",
            metrosSemiCubiertos: 4.0,
            id: "a0L1U000004vtg5UAA",
            name: "UF 0603",
            piso: "6",
            imagenesUnidad: null,
          },
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: null,
          contactoDescripcion:
            "<p>2 ambientes con balcón</p> <p>Total 44m2</p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009W6J0QAK",
          landing: "a151U000004D9UWQA0",
          name: "UF 0504",
          ocultar: true,
          ordenInterno: null,
          orden: "NaN",
          recordType: "0121U000000KV0LQAW",
          subtitulo: "Total 44m2",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "2 ambientes con balcón",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen: "",
          unidadFuncional: {
            ambiente: "2 Ambientes",
            estado: "Vendida",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 47.0,
            metrosCuadrados: 47.0,
            metrosCubiertos: 40.0,
            metrosDescubiertos: "NaN",
            metrosSemiCubiertos: 7.0,
            id: "a0L1U000004vtdVUAQ",
            name: "UF 0504",
            piso: "5",
            imagenesUnidad: null,
          },
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: null,
          contactoDescripcion:
            "<p>2 ambientes con balcón</p> <p>Total 44m2</p> <p>40m2 Cubierto - 4m2 Semicubierto</p>",
          descripcion: "40m2 Cubierto - 4m2 Semicubierto",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009W6IzQAK",
          landing: "a151U000004D9UWQA0",
          name: "UF 0503",
          ocultar: true,
          ordenInterno: null,
          orden: "NaN",
          recordType: "0121U000000KV0LQAW",
          subtitulo: "Total 44m2",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "2 ambientes con balcón",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen: "",
          unidadFuncional: {
            ambiente: "Monoambiente",
            estado: "Vendida",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 44.0,
            metrosCuadrados: 44.0,
            metrosCubiertos: 40.0,
            metrosDescubiertos: "NaN",
            metrosSemiCubiertos: 4.0,
            id: "a0L1U000004vtdBUAQ",
            name: "UF 0503",
            piso: "5",
            imagenesUnidad: null,
          },
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: null,
          contactoDescripcion: "<p></p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009W6IBQA0",
          landing: "a151U000004D9UWQA0",
          name: "UF0104 Niceto",
          ocultar: true,
          ordenInterno: null,
          orden: "NaN",
          recordType: "0121U000000KV0LQAW",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen:
            "https://rosbacopartners.com/wp-content/uploads/2020/12/niceto9.jpg",
          unidadFuncional: {
            ambiente: "2 Ambientes",
            estado: "Disponible",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 47.0,
            metrosCuadrados: 47.0,
            metrosCubiertos: 40.0,
            metrosDescubiertos: "NaN",
            metrosSemiCubiertos: 7.0,
            id: "a0L1U000004vtcIUAQ",
            name: "UF 0104",
            piso: "1",
            imagenesUnidad: null,
          },
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: null,
          contactoDescripcion:
            "<p>2 Ambientes c/balcón</p> <p>44m2 Total</p> <p>40m2 Cubiertos - 4m2 semicubiertos</p>",
          descripcion: "40m2 Cubiertos - 4m2 semicubiertos",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009W6ILQA0",
          landing: "a151U000004D9UWQA0",
          name: "UF0203",
          ocultar: true,
          ordenInterno: null,
          orden: "NaN",
          recordType: "0121U000000KV0LQAW",
          subtitulo: "44m2 Total",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "2 Ambientes c/balcón",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen:
            "https://rosbacopartners.com/wp-admin/upload.php?item=1280",
          unidadFuncional: {
            ambiente: "Monoambiente",
            estado: "Disponible",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 44.0,
            metrosCuadrados: 44.0,
            metrosCubiertos: 40.0,
            metrosDescubiertos: "NaN",
            metrosSemiCubiertos: 4.0,
            id: "a0L1U000004vtcKUAQ",
            name: "UF 0203",
            piso: "2",
            imagenesUnidad: null,
          },
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: null,
          contactoDescripcion:
            "<p>2 ambientes balcon contrafrente</p> <p>Total 45m2</p> <p>40m2 Cubiertos - 5m2 semicubiertos)</p>",
          descripcion: "40m2 Cubiertos - 5m2 semicubiertos)",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009W6IpQAK",
          landing: "a151U000004D9UWQA0",
          name: "UF 0303",
          ocultar: true,
          ordenInterno: null,
          orden: "NaN",
          recordType: "0121U000000KV0LQAW",
          subtitulo: "Total 45m2",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "2 ambientes balcon contrafrente",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen:
            "https://rosbacopartners.com/wp-admin/upload.php?item=1273",
          unidadFuncional: {
            ambiente: "Monoambiente",
            estado: "Vendida",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 44.0,
            metrosCuadrados: 44.0,
            metrosCubiertos: 40.0,
            metrosDescubiertos: "NaN",
            metrosSemiCubiertos: 4.0,
            id: "a0L1U000004vtcmUAA",
            name: "UF 0303",
            piso: "3",
            imagenesUnidad: null,
          },
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: null,
          contactoDescripcion: "<p></p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009W6J9QAK",
          landing: "a151U000004D9UWQA0",
          name: "UF 0604",
          ocultar: true,
          ordenInterno: null,
          orden: "NaN",
          recordType: "0121U000000KV0LQAW",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen: "",
          unidadFuncional: {
            ambiente: "2 Ambientes",
            estado: "Vendida",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 47.0,
            metrosCuadrados: 47.0,
            metrosCubiertos: 40.0,
            metrosDescubiertos: "NaN",
            metrosSemiCubiertos: 7.0,
            id: "a0L1U000004vtgAUAQ",
            name: "UF 0604",
            piso: "6",
            imagenesUnidad: null,
          },
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: null,
          contactoDescripcion: "<p></p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009W6JJQA0",
          landing: "a151U000004D9UWQA0",
          name: "UF 0704",
          ocultar: true,
          ordenInterno: null,
          orden: "NaN",
          recordType: "0121U000000KV0LQAW",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen: "",
          unidadFuncional: {
            ambiente: "2 Ambientes",
            estado: "Disponible",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 47.0,
            metrosCuadrados: 47.0,
            metrosCubiertos: 40.0,
            metrosDescubiertos: "NaN",
            metrosSemiCubiertos: 7.0,
            id: "a0L1U000004vtgLUAQ",
            name: "UF 0704",
            piso: "7",
            imagenesUnidad: null,
          },
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: null,
          contactoDescripcion: "<p></p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009W6JdQAK",
          landing: "a151U000004D9UWQA0",
          name: "UF 0903",
          ocultar: true,
          ordenInterno: null,
          orden: "NaN",
          recordType: "0121U000000KV0LQAW",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen: "",
          unidadFuncional: {
            ambiente: "3 Ambientes",
            estado: "Reservado Desarrolladora",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 56.0,
            metrosCuadrados: 47.6,
            metrosCubiertos: 40.0,
            metrosDescubiertos: 12.0,
            metrosSemiCubiertos: 4.0,
            id: "a0L1U000004vtgtUAA",
            name: "UF 0903",
            piso: "9",
            imagenesUnidad: null,
          },
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: null,
          contactoDescripcion:
            "<p>2 ambientes</p> <p>Total 47m2</p> <p>40m2 Cubiertos - 7m2 Semicubiertos</p>",
          descripcion: "40m2 Cubiertos - 7m2 Semicubiertos",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009W6IGQA0",
          landing: "a151U000004D9UWQA0",
          name: "UF0204",
          ocultar: true,
          ordenInterno: null,
          orden: "NaN",
          recordType: "0121U000000KV0LQAW",
          subtitulo: "Total 47m2",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "2 ambientes",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen:
            "https://rosbacopartners.com/wp-content/uploads/2020/12/niceto10.jpg",
          unidadFuncional: {
            ambiente: "2 Ambientes",
            estado: "Vendida",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 47.0,
            metrosCuadrados: 47.0,
            metrosCubiertos: 40.0,
            metrosDescubiertos: "NaN",
            metrosSemiCubiertos: 7.0,
            id: "a0L1U000004vtccUAA",
            name: "UF 0204",
            piso: "2",
            imagenesUnidad: null,
          },
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: [2263, 1524, 2244, 1731, 1884, 1664, 1894, 1438],
          contactoDescripcion:
            "<p>2 ambientes con balcón</p> <p>Total 47m2</p> <p>40m2 Cubiertos -7m2 semicubiertos</p>",
          descripcion: "40m2 Cubiertos -7m2 semicubiertos",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009W6IlQAK",
          landing: "a151U000004D9UWQA0",
          name: "UF0404",
          ocultar: true,
          ordenInterno: null,
          orden: "NaN",
          recordType: "0121U000000KV0LQAW",
          subtitulo: "Total 47m2",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "2 ambientes con balcón",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen: "",
          unidadFuncional: {
            ambiente: "2 Ambientes",
            estado: "Disponible",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 47.0,
            metrosCuadrados: 47.0,
            metrosCubiertos: 40.0,
            metrosDescubiertos: "NaN",
            metrosSemiCubiertos: 7.0,
            id: "a0L1U000004vtd1UAA",
            name: "UF 0404",
            piso: "4",
            imagenesUnidad: null,
          },
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: null,
          contactoDescripcion: "<p></p> <p></p> <p></p>",
          descripcion: "",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009W6JYQA0",
          landing: "a151U000004D9UWQA0",
          name: "UF 0904",
          ocultar: true,
          ordenInterno: null,
          orden: "NaN",
          recordType: "0121U000000KV0LQAW",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen: "",
          unidadFuncional: {
            ambiente: "3 Ambientes",
            estado: "Reservado Desarrolladora",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 34.0,
            metrosCuadrados: 34.0,
            metrosCubiertos: 30.0,
            metrosDescubiertos: "NaN",
            metrosSemiCubiertos: 4.0,
            id: "a0L1U000004vtgyUAA",
            name: "UF 0904",
            piso: "9",
            imagenesUnidad: null,
          },
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: null,
          contactoDescripcion:
            "<p>2 ambientes con balcón contrafrente</p> <p>44m2</p> <p>40m2 Cubiertos - 4m2 Semicubiertos</p>",
          descripcion: "40m2 Cubiertos - 4m2 Semicubiertos",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009W6IuQAK",
          landing: "a151U000004D9UWQA0",
          name: "UF 0403",
          ocultar: true,
          ordenInterno: null,
          orden: "NaN",
          recordType: "0121U000000KV0LQAW",
          subtitulo: "44m2",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "2 ambientes con balcón contrafrente",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen: "",
          unidadFuncional: {
            ambiente: "Monoambiente",
            estado: "Vendida",
            metrosAmenities: "NaN",
            metrosCuadradosTotales: 44.0,
            metrosCuadrados: 44.0,
            metrosCubiertos: 40.0,
            metrosDescubiertos: "NaN",
            metrosSemiCubiertos: 4.0,
            id: "a0L1U000004vtcxUAA",
            name: "UF 0403",
            piso: "4",
            imagenesUnidad: null,
          },
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: null,
          contactoDescripcion:
            "<p>EDIFICIO INTELIGENTE QUE TE CUIDA A VOS Y AL PLANETA</p> <p>MOOD NICETO VEGA - ECOFRIENDLY</p> <p>Smart Building gestionado por lo último en tecnología domótica: el sistema integral de gestión central hace un uso súper eficiente de los recursos con hasta un 30% de ahorro de energía, que se traduce en bajas expensas.</p>",
          descripcion:
            "Smart Building gestionado por lo último en tecnología domótica: el sistema integral de gestión central hace un uso súper eficiente de los recursos con hasta un 30% de ahorro de energía, que se traduce en bajas expensas.",
          descripcionhex: "#353330",
          descripcionalign: "left",
          id: "a161U000009I9nnQAC",
          landing: "a151U000004D9UWQA0",
          name: "Texto",
          ocultar: true,
          ordenInterno: "NaN",
          orden: "NaN",
          recordType: "0121U000000KV0fQAG",
          subtitulo: "MOOD NICETO VEGA - ECOFRIENDLY",
          subtitulohex: "#CF8D1A",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "EDIFICIO INTELIGENTE QUE TE CUIDA A VOS Y AL PLANETA",
          titulohex: "#030303",
          tituloalign: "left",
          urlImagen: "",
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: null,
          contactoDescripcion:
            "<p>Excelente Ubicación</p> <p></p> <p>Está ubicado en Palermo Hollywood, una de las zonas más buscadas por el público joven y dinámico. Con hectáreas de espacios verdes para el disfrute en familia o prácticas de de deporte a toda hora.</p>",
          descripcion:
            "Está ubicado en Palermo Hollywood, una de las zonas más buscadas por el público joven y dinámico. Con hectáreas de espacios verdes para el disfrute en familia o prácticas de de deporte a toda hora.",
          descripcionhex: "#000000",
          descripcionalign: "left",
          id: "a161U000009I9nBQAS",
          landing: "a151U000004D9UWQA0",
          name: "Text Slider Amenities 3",
          ocultar: true,
          ordenInterno: "NaN",
          orden: "NaN",
          recordType: "0121U000000KV0pQAG",
          subtitulo: "",
          subtitulohex: "#000000",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "Excelente Ubicación",
          titulohex: "#000000",
          tituloalign: "left",
          urlImagen:
            "https://rosbacopartners.com/wp-content/uploads/2020/12/NICETO-14.jpg",
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: null,
          contactoDescripcion:
            "<p>ECO-FRIENDLY</p> <p>Hasta un 30% de Ahorro en Gastos de Energía</p> <p>Cumpliendo con nuestro compromiso de sustentabilidad con un uso súper eficiente de los recursos, reduciendo el consumo de luz, agua o gas.</p>",
          descripcion:
            "Cumpliendo con nuestro compromiso de sustentabilidad con un uso súper eficiente de los recursos, reduciendo el consumo de luz, agua o gas.",
          descripcionhex: "#353532",
          descripcionalign: "left",
          id: "a161U000009I9n6QAC",
          landing: "a151U000004D9UWQA0",
          name: "Slider Text Amenities 2",
          ocultar: true,
          ordenInterno: "NaN",
          orden: "NaN",
          recordType: "0121U000000KV0pQAG",
          subtitulo: "Hasta un 30% de Ahorro en Gastos de Energía",
          subtitulohex: "#F1C40F",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "ECO-FRIENDLY",
          titulohex: "#030303",
          tituloalign: "left",
          urlImagen:
            "https://rosbacopartners.com/wp-content/uploads/2020/11/20-Fitness-min.jpg",
        },
        {
          ancla: "",
          atributoClase: "",
          atributo: "",
          background: "dark",
          bghex: "#FFFFFF",
          coordenadasSombra: null,
          contactoDescripcion:
            "<p>Amenities</p> <p>Laundry - Terraza - Parrilla</p> <p>Solarium con duchas - Cocheras & Car Wash - Bike Rack con bicis de cortesía – Lockers – Charging points - Wifi en áreas comunes</p>",
          descripcion:
            "Solarium con duchas - Cocheras & Car Wash - Bike Rack con bicis de cortesía – Lockers – Charging points - Wifi en áreas comunes",
          descripcionhex: "#353532",
          descripcionalign: "left",
          id: "a161U000009I9n1QAC",
          landing: "a151U000004D9UWQA0",
          name: "Texto Slider Amenities",
          ocultar: true,
          ordenInterno: "NaN",
          orden: "NaN",
          recordType: "0121U000000KV0pQAG",
          subtitulo: "Laundry - Terraza - Parrilla",
          subtitulohex: "#F1C40F",
          subtituloalign: "left",
          textoAlineacion: "left",
          titulo: "Amenities",
          titulohex: "#030303",
          tituloalign: "left",
          urlImagen:
            "https://rosbacopartners.com/wp-content/uploads/2020/11/PARRILLA-DUCHA-1.jpg",
        },
      ],
    },
  ],
  googleAnalytics: "G-BMJ9373JS5",
};
export default data;
